#!/bin/bash

python ./src/main.py \
    --n_in 2 \
    --n_h 200 \
    --n_out 1 \
    --num_layers 1 \
    --task Random \
    --randomType Uniform \
    --seq 100 \
    --numTr 5 \
    --numVl 5 \
    --numTe 5000 \
    --batch_size_tr 5 \
    --batch_size_vl 5 \
    --batch_size_te 5000 \
    --t1 5 \
    --t2 9 \
    --num_epochs 60 \
    --learning_rate 0.01 \
    --optimizerFn SGD \
    --lossFn mse \
    --mode experiment \
    --checkpoint_freq 20 \
    --seed 2 \
    --projectName "rnn-test-rnnonlytest" \
    --logger "wandb" \
    --performance_samples 9 \
    --init_scheme ZeroInit \
    --activation_fn tanh \
    --log_freq 1 \
    --meta_learning_rate 0.0001 \
    --l2_regularization 0 \
    --is_oho 0 \
    --time_chunk_size 10
