#!/bin/bash

python ./src/main.py \
    --n_in 2 \
    --n_h 30 \
    --n_out 1 \
    --num_layers 1 \
    --task Random \
    --init_scheme RandomInit \
    --seq 10 \
    --numTr 1000 \
    --numVl 1000 \
    --numTe 5000 \
    --batch_size_tr 1000 \
    --batch_size_vl 1000 \
    --batch_size_te 1000 \
    --t1 2 \
    --t2 2 \
    --num_epochs 500 \
    --learning_rate 0.001 \
    --optimizerFn SGD \
    --lossFn mse \
    --mode test \
    --checkpoint_freq 10 \
    --seed 1 \
    --projectName "rnn-test-ohotest1" \
    --logger "wandb" \
    --performance_samples 9 \
    --activation_fn relu \
    --log_freq 1 \
    --meta_learning_rate 0.00001 \
    --l2_regularization 0.0
