services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: rnn-test
    volumes:
      - ..:/rnn-test:cached
    ports:
      - "10000:10000"
    # command: "/bin/bash -c 'micromamba shell init --shell bash --root-prefix=/opt/conda && source ~/.bashrc && micromamba activate master && cd /rnn-test && git config --global --add safe.directory /rnn-test && mkdir ~/notebooks && jupyter lab --notebook-dir=~/notebooks --ip=\"0.0.0.0\" --port=8888 --no-browser --allow-root'" # command: sleep infinity
    command: "sleep infinity"
