name: ci

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile 
      - .github/workflows/** 
      - src/**
      - entrypoint.sh
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  docker:
    strategy:
      matrix:
        variant: [cpu, gpu] 
    uses: thewillyP/ReusableWorkflow/.github/workflows/main.yml@main
    with:
      image_name: rnn-test
      tag: 1.0.${{ github.run_number }}-${{ matrix.variant }}
      build_args: VARIANT=${{ matrix.variant }} 
    secrets: inherit
